### ISSUE TITLE
Biome restriction for buildings doesn't work

### ISSUE THREAD

**Issue by LuminousLizard** [voxeltycoon/docs#7]
The restriction to a specific biome doesn't work. I want a city building to appear only in arctic biome.
The wiki says:
```
{
  "Uri": "arab_buildings/arab_house5.house",
  "ProportionalCount": 50,
  "Density": 0.0,
  "Biomes": [
    "arab_buildings/desert2.biome"
  ]
}
```
I tried it with:
```
  "Biomes": [
    "base/arctic.biome"
  ]
```
to bind it to the vanilla arctic biome but it doesn't work. 

LuminousLizard

**Comment by andrewpey** [comment]
That guide is written by a community member, and it's targeting `0.80` version of the game. It hasn't been updated to the current version yet.

The asset format has changed, you can look for the exact format in the base game files.

Specifically, there was added the `Tags` property which can be used to define biomes where the building should appear. If a `.biome` asset has a matching tag in the `Tags` property, a building will spawn in that biome.

Note that, as of [0.86](https://voxeltycoon.xyz/changelog#0.86), the base biomes do not have `Tags` property set by default, but they can be [patched](https://docs.voxeltycoon.xyz/assets/patch-asset/).

Hope this helps!
